sudo: false

language: node_js

node_js:
  - "0.10"
  - "0.11"
  - "0.12"
  - "4.0"

addons:
  code_climate:
    repo_token: b96c8e14d13e6e0eac109776042700ebba5cddd019d9031fc476d8110842920f

after_script:
  - npm install codeclimate-test-reporter
  - codeclimate-test-reporter < coverage/lcov.info
